backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: 'cenovnik'
    preview: false
    label: 'Cenovnik'
    folder: 'content/cenovnik'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Naslov', name: 'title', widget: 'string'}
      - {label: 'Objavljeno', name: 'objavljeno', widget: 'string', required: false}
      - {label: 'Tekst', name: 'body', widget: 'text'}


  - name: testimonials
    label: Testimonials
    widget: list
    preview: false
    create: true
    summary: '{{fields.quote}} - {{fields.author.name}}'
    fields:
      - {label: 'quote', name: 'Quote', widget: 'string'}
      - {label: 'author', name: 'Quote', widget: 'string', fields: -{label: 'Name', name: 'name', widget: 'string'} -{label: 'Surname', name: 'surname', widget: 'string'} }



