backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: 'cenovnik'
    preview: false
    label: 'Cenovnik'
    folder: 'content/cenovnik'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Naslov', name: 'title', widget: 'string'}
      - {label: 'Objavljeno', name: 'objavljeno', widget: 'string', required: false}
      - {label: 'Tekst', name: 'body', widget: 'text'}


  - name: testimonials
    label: Testimonials
    widget: list
    summary: '{{fields.quote}} - {{fields.author.name}}'
    fields:
      - name: quote
        label: Quote
        widget: string
        default: Everything is awesome!
      - name: author
        label: Author
        widget: object
        fields:
          - name: name
            label: Name
            widget: string
            default: Emmet
          - name: avatar
            label: Avatar
            widget: image
