backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: 'cenovnik'
    preview: false
    label: 'Cenovnik'
    folder: 'content/cenovnik'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Naslov', name: 'title', widget: 'string'}
      - {label: 'Objavljeno', name: 'objavljeno', widget: 'string', required: false}
      - {label: 'Tekst', name: 'body', widget: 'text'}


  - name: 'testimonials'
    label: 'Testimonials'
    folder: 'content/usluge'
    widget: list
    preview: false
    create: true
    fields:
      - {label: 'quote', name: 'Quote', widget: 'string'}

  - name: 'profile'
    label: 'Profile'
    widget: 'object'
    fields:
      - name: public
        label: Public
        widget: boolean
        default: true
      - name: name
        label: Name
        widget: string
      - name: 'birthdate'
        label: 'Birthdate'
        widget: 'date'
        default: ''
        format: 'MM/DD/YYYY'
      - name: 'address'
        label: 'Address'
        widget: 'object'
        collapsed: true
        fields:
          - name: street
            label: Street Address
            widget: string
          - name: city
            label: City
            widget: string
          - name: post-code
            label: Postal Code
            widget: string



