backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/

collections:
#  - name: 'cena'
#    preview: false
#    label: 'Cena'
#    folder: 'content/cenovnik'
#    create: true
#    slug: '{{slug}}'
#    fields:
#      - {label: 'Naslov', name: 'title', widget: 'string'}
#      - {label: 'Objavljeno', name: 'objavljeno', widget: 'string', required: false}
#      - {label: 'Tekst', name: 'body', widget: 'text'}


  - name: 'testimonials'
    label: 'Testimonials'
    folder: 'content/usluge'
    widget: list
    preview: false
    create: true
    fields:
      - {label: 'quote', name: 'Quote', widget: 'string'}

  - label: "Gallery"
    name: "galleryImages"
    widget: "list"
    folder: 'content/usluge'
    preview: false
    create: true
    fields:
      - { label: 'Nesto', name: 'title', widget: 'string' }
      - label: 'Author'
        name: 'author'
        widget: 'list'
        create: true
        fields:
          - { label: 'Name', name: 'name', widget: 'string'}
          - { label: 'Avatar', name: 'avatar', widget: 'string'}


#trebalo bi biti dobro
  - label: "Cenovnik"
    name: "cena"
    widget: "list"
    folder: 'content/cenovnik'
    preview: false
    create: true
    fields:
      - { label: 'Usluga', name: 'title', widget: 'string' }
      - label: 'Vrsta'
        name: 'vrsta'
        widget: 'list'
        create: true
        fields:
          - { label: 'Vrsta usluge', name: 'vrstaUsluge', widget: 'string' }
          - { label: 'Cena usluge', name: 'cenaUsluge', widget: 'string' }


  - label: "Objava"
    name: 'objava'
    folder: 'content/objava'
    preview: false
    create: true
    fields:
      - { label: 'Obavestenje', name: 'title', widget: 'string' }
      - { label: 'Objavi', name: 'objavi', widget: 'boolean' }
      - { label: 'Tekst', name: 'body', widget: 'text' }


  - label: "Efekti"
    name: 'efekti'
    folder: 'content/efekti'
    preview: false
    create: false
    fields:
#      - { label: 'Tekst objave', name: 'title', widget: 'text' }
      - { label: 'Efekt', name: 'title', widget: 'string' }
      - { label: 'Ukljuci', name: 'ukljuceno', widget: 'boolean' }
