backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: 'cenovnik'
    preview: false
    label: 'Cenovnik'
    folder: 'content/cenovnik'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Naslov', name: 'title', widget: 'string'}
      - {label: 'Objavljeno', name: 'objavljeno', widget: 'string', required: false}
      - {label: 'Tekst', name: 'body', widget: 'text'}


  - name: 'testimonials'
    label: 'Testimonials'
    folder: 'content/usluge'
    widget: list
    preview: false
    create: true
    fields:
      - {label: 'quote', name: 'Quote', widget: 'string'}

  - name: "nest"
    label: "Nesto"
    widget: "list"
    preview: false
    create: true
    fields:
      - { label: 'Quote', name: 'quote', widget: 'string', default: "Everything is awesome!" }
      - label: "Author"
        name: "author"
        widget: 'object'
        fields:
          - { label: 'Name', name: 'name', widget: 'string', default: "Emmet" }
          - { label: 'Prezime', name: 'prezime', widget: 'string' }



